name: build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:

permissions: {}

jobs:
  build:
    uses: portapps/.github/.github/workflows/app-build.yml@master
    permissions:
      pull-requests: read
      contents: write
